# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'convey (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for convey (iOS)

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '8.3.0-beta'

end

target 'convey (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for convey (macOS)

end

target 'conveyTests' do

  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '8.3.0-beta'

end
